# @package _group_
csv:
    _target_: pytorch_lightning.loggers.csv_logs.CSVLogger
    save_dir: "csv/"
    name: "csv"

tensorboard:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: "tensorboard/"
    name: "default"