_target_: src.datamodules.xview2_datamodule.Xview2DataModule

root: ${data_dir}
mean_arr_path: ${data_dir}/meta/mean.npy
batch_size: 32
train_val_test_split: [0.75, 0.25]
num_workers: 10
pin_memory: True
crop_size: 256
